<?php
// function bakery_user_menu() {
//     $items = array();
//     $items['welcome_user'] = array(
//         'title' => "Hi There!",
//         'page callback' => 'welcome_user_page',
//         'access callback' => TRUE,
//         'type' => MENU_CALLBACK,
//     );
//     return $items;
// }
//
// function bakery_user_user_login() {
//     $_GET['destination'] = 'welcome_user';
// }
//
// function welcome_user_page() {
//     return '<p>Welcome to Cameron\'s Bakery!</p>';
// }
